site_name: FDC3 Desktop Agent
site_description: Documentation for the FDC3 Desktop Agent Python implementation
site_author: Joel Squire
site_url: https://jnsquire.github.io/py-fdc3-desktop-agent/

docs_dir: documentation

theme:
  name: readthedocs

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_div_format

extra_javascript:
  - assets/mermaid.min.js
  - assets/mermaid-init.js

extra_css:
  - assets/mermaid-zoom.css

nav:
  - Overview: index.md
  - Getting started: getting-started.md
  - Configuration: configuration.md
  - Automation: automation.md
  - Deployments: deployments.md
  - Bridging (experimental): bridging.md
  - Embedding API: embedding-api.md
  - Plugins: plugins.md
  - Data Science Integration: notebooks.md
  - External intent handlers: external-intent-handlers.md
  - Private channels: private-channels.md
  - Docker deployment: docker.md
  - System flowchart: system_flowchart.md
  - API Reference:
      - API Guide: api-guide.md
      - Desktop Agent: api.md

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths:
            - .
          options:
            docstring_style: google
            heading_level: 3
            show_root_heading: true
            members_order: source
            show_signature_annotations: false
            signature_crossrefs: true
            separate_signature: true
            show_symbol_type_heading: true
            show_symbol_type_toc: true
            show_source: false
            show_if_no_docstring: false
            merge_init_into_class: true
            inherited_members: true
            filters:
              - "!^_"
