[pytest]
filterwarnings =
    ignore:websockets.legacy is deprecated:DeprecationWarning
    ignore:websockets.server.WebSocketServerProtocol is deprecated:DeprecationWarning
    ignore:remove second argument of ws_handler:DeprecationWarning

# Ensure pytest-asyncio operates in `auto` mode so async fixtures are handled as before
asyncio_mode = auto
