# generated by datamodel-codegen:
#   filename:  https://raw.githubusercontent.com/finos/FDC3/refs/heads/fdc3-for-web/schemas/api/api.schema.json
#   timestamp: 2025-12-13T04:44:53+00:00

from __future__ import annotations

import uuid
from datetime import datetime
from enum import Enum
from typing import Any, Dict, List, Optional, Union

from pydantic import BaseModel, ConfigDict, Field, RootModel

from . import context as context_1
from fdc3.models.identifiers import AppIdentifier


class Fdc3DesktopAgentApiSchemas(RootModel[Any]):
    root: Any = Field(..., title="FDC3 Desktop Agent API Schemas")


class Icon(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    src: str = Field(..., description="The icon url.", title="src")
    size: Optional[str] = Field(
        None,
        description="The icon dimension, formatted as `<height>x<width>`.",
        title="size",
    )
    type: Optional[str] = Field(
        None,
        description="Icon media type. If not present the Desktop Agent may use the src file extension.",
        title="type",
    )


class Image(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    src: str = Field(..., description="The image url.", title="src")
    size: Optional[str] = Field(
        None,
        description="The image dimension, formatted as `<height>x<width>`.",
        title="size",
    )
    type: Optional[str] = Field(
        None,
        description="Image media type. If not present the Desktop Agent may use the src file extension.",
        title="type",
    )
    label: Optional[str] = Field(
        None, description="Caption for the image.", title="label"
    )


class AppMetadata(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    name: Optional[str] = Field(
        None,
        description="The 'friendly' app name. \nThis field was used with the `open` and `raiseIntent` calls in FDC3 <2.0, which now require an `AppIdentifier` wth `appId` set. \nNote that for display purposes the `title` field should be used, if set, in preference to this field.",
        title="name",
    )
    version: Optional[str] = Field(
        None, description="The Version of the application.", title="version"
    )
    instanceMetadata: Optional[Dict[str, Any]] = Field(
        None,
        description="An optional set of, implementation specific, metadata fields that can be used to disambiguate instances, such as a window title or screen position. Must only be set if `instanceId` is set.",
        title="instanceMetadata",
    )
    title: Optional[str] = Field(
        None,
        description="A more user-friendly application title that can be used to render UI elements.",
        title="title",
    )
    tooltip: Optional[str] = Field(
        None,
        description="A tooltip for the application that can be used to render UI elements.",
        title="tooltip",
    )
    description: Optional[str] = Field(
        None,
        description="A longer, multi-paragraph description for the application that could include markup.",
        title="description",
    )
    icons: Optional[List[Icon]] = Field(
        None,
        description="A list of icon URLs for the application that can be used to render UI elements.",
        title="icons",
    )
    screenshots: Optional[List[Image]] = Field(
        None,
        description="Images representing the app in common usage scenarios that can be used to render UI elements.",
        title="screenshots",
    )
    resultType: Optional[str] = Field(
        None,
        description='The type of output returned for any intent specified during resolution. May express a particular context type (e.g. "fdc3.instrument"), channel (e.g. "channel") or a channel that will receive a specified type (e.g. "channel<fdc3.instrument>").',
        title="resultType",
    )
    appId: str = Field(
        ...,
        description="The unique application identifier located within a specific application directory instance. An example of an appId might be 'app@sub.root'.",
        title="appId",
    )
    instanceId: Optional[str] = Field(
        None,
        description="An optional instance identifier, indicating that this object represents a specific instance of the application described.",
        title="instanceId",
    )
    desktopAgent: Optional[str] = Field(
        None,
        description="The Desktop Agent that the app is available on. Used in Desktop Agent Bridging to identify the Desktop Agent to target.",
        title="desktopAgent",
    )


class IntentMetadata(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    name: str = Field(
        ...,
        description="The unique name of the intent that can be invoked by the raiseIntent call.",
        title="name",
    )
    displayName: Optional[str] = Field(
        None, description="Display name for the intent.", title="displayName"
    )


class AppIntent(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    intent: IntentMetadata = Field(
        ...,
        description="Details of the intent whose relationship to resolving applications is being described.",
        title="intent",
    )
    apps: List[AppMetadata] = Field(
        ...,
        description="Details of applications that can resolve the intent.",
        title="apps",
    )


class DisplayMetadata(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    name: Optional[str] = Field(
        None,
        description='A user-readable name for this channel, e.g: `"Red"`.',
        title="name",
    )
    color: Optional[str] = Field(
        None,
        description="The color that should be associated within this channel when displaying this channel in a UI, e.g: `0xFF0000`.",
        title="color",
    )
    glyph: Optional[str] = Field(
        None,
        description="A URL of an image that can be used to display this channel.",
        title="glyph",
    )


class Type(Enum):
    app = "app"
    private = "private"
    user = "user"


class Channel(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    id: str = Field(
        ..., description="Constant that uniquely identifies this channel.", title="id"
    )
    type: Type = Field(
        ...,
        description='Uniquely defines each channel type.\nCan be "user", "app" or "private".',
        title="type",
    )
    displayMetadata: Optional[DisplayMetadata] = Field(
        None,
        description="Channels may be visualized and selectable by users. DisplayMetadata may be used to provide hints on how to see them.\nFor App channels, displayMetadata would typically not be present.",
        title="displayMetadata",
    )


class ContextMetadata(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    source: AppIdentifier = Field(
        ...,
        description="Identifier for the app instance that sent the context and/or intent.",
        title="source",
    )


class DesktopAgentIdentifier(BaseModel):
    desktopAgent: str = Field(
        ...,
        description="Used in Desktop Agent Bridging to attribute or target a message to a\nparticular Desktop Agent.",
        title="desktopAgent",
    )


class OpenError(Enum):
    AppNotFound = "AppNotFound"
    AppTimeout = "AppTimeout"
    DesktopAgentNotFound = "DesktopAgentNotFound"
    ErrorOnLaunch = "ErrorOnLaunch"
    MalformedContext = "MalformedContext"
    ResolverUnavailable = "ResolverUnavailable"


class ResolveError(Enum):
    DesktopAgentNotFound = "DesktopAgentNotFound"
    IntentDeliveryFailed = "IntentDeliveryFailed"
    MalformedContext = "MalformedContext"
    NoAppsFound = "NoAppsFound"
    ResolverTimeout = "ResolverTimeout"
    ResolverUnavailable = "ResolverUnavailable"
    TargetAppUnavailable = "TargetAppUnavailable"
    TargetInstanceUnavailable = "TargetInstanceUnavailable"
    UserCancelledResolution = "UserCancelledResolution"


class ResultError(Enum):
    IntentHandlerRejected = "IntentHandlerRejected"
    NoResultReturned = "NoResultReturned"


class ChannelError(Enum):
    AccessDenied = "AccessDenied"
    CreationFailed = "CreationFailed"
    MalformedContext = "MalformedContext"
    NoChannelFound = "NoChannelFound"


class BridgingError(Enum):
    AgentDisconnected = "AgentDisconnected"
    NotConnectedToBridge = "NotConnectedToBridge"
    ResponseToBridgeTimedOut = "ResponseToBridgeTimedOut"
    MalformedMessage = "MalformedMessage"


class OptionalFeatures(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    OriginatingAppMetadata: bool = Field(
        ...,
        description="Used to indicate whether the exposure of 'originating app metadata' for\ncontext and intent messages is supported by the Desktop Agent.",
        title="OriginatingAppMetadata",
    )
    UserChannelMembershipAPIs: bool = Field(
        ...,
        description="Used to indicate whether the optional `fdc3.joinUserChannel`,\n`fdc3.getCurrentChannel` and `fdc3.leaveCurrentChannel` are implemented by\nthe Desktop Agent.",
        title="UserChannelMembershipAPIs",
    )
    DesktopAgentBridging: bool = Field(
        ...,
        description="Used to indicate whether the experimental Desktop Agent Bridging\nfeature is implemented by the Desktop Agent.",
        title="DesktopAgentBridging",
    )


class BaseImplementationMetadata(BaseModel):
    fdc3Version: str = Field(
        ...,
        description="The version number of the FDC3 specification that the implementation provides.\nThe string must be a numeric semver version, e.g. 1.2 or 1.2.1.",
        title="fdc3Version",
    )
    provider: str = Field(
        ...,
        description="The name of the provider of the Desktop Agent implementation (e.g. Finsemble, Glue42, OpenFin etc.).",
        title="provider",
    )
    providerVersion: Optional[str] = Field(
        None,
        description="The version of the provider of the Desktop Agent implementation (e.g. 5.3.0).",
        title="providerVersion",
    )
    optionalFeatures: OptionalFeatures = Field(
        ...,
        description="Metadata indicating whether the Desktop Agent implements optional features of\nthe Desktop Agent API.",
        title="optionalFeatures",
    )


class ImplementationMetadata(BaseImplementationMetadata):
    model_config = ConfigDict(
        extra="forbid",
    )
    appMetadata: Optional[AppMetadata] = Field(
        None,
        description="The calling application instance's own metadata, according to the Desktop Agent (MUST include at least the `appId` and `instanceId`).",
        title="appMetadata",
    )
    fdc3Version: str
    provider: str
    providerVersion: Optional[str] = None
    optionalFeatures: OptionalFeatures


class IntentResolution(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    source: AppIdentifier = Field(
        ...,
        description="Identifier for the app instance that was selected (or started) to resolve the intent.\n`source.instanceId` MUST be set, indicating the specific app instance that\nreceived the intent.",
        title="source",
    )
    intent: str = Field(
        ...,
        description="The intent that was raised. May be used to determine which intent the user\nchose in response to `fdc3.raiseIntentForContext()`.",
        title="intent",
    )


class IntentResult2(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    channel: Channel


class BaseContext(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    type: str
    name: Optional[str] = None
    id: Optional[Dict[str, Any]] = None


class DocumentedContext(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    type: str = Field(
        ...,
        description="The type property is the only _required_ part of the FDC3 context data schema. The FDC3 [API](https://fdc3.finos.org/docs/api/spec) relies on the `type` property being present to route shared context data appropriately.\n\nFDC3 [Intents](https://fdc3.finos.org/docs/intents/spec) also register the context data types they support in an FDC3 [App Directory](https://fdc3.finos.org/docs/app-directory/overview), used for intent discovery and routing.\n\nStandardized FDC3 context types have well-known `type` properties prefixed with the `fdc3` namespace, e.g. `fdc3.instrument`. For non-standard types, e.g. those defined and used by a particular organization, the convention is to prefix them with an organization-specific namespace, e.g. `blackrock.fund`.\n\nSee the [Context Data Specification](https://fdc3.finos.org/docs/context/spec) for more information about context data types.",
        title="Type",
    )
    name: Optional[str] = Field(
        None,
        description="Context data objects may include a name property that can be used for more information, or display purposes. Some derived types may require the name object as mandatory, depending on use case.",
        title="Name",
    )
    id: Optional[Dict[str, Any]] = Field(
        None,
        description="Context data objects may include a set of equivalent key-value pairs that can be used to help applications identify and look up the context type they receive in their own domain. The idea behind this design is that applications can provide as many equivalent identifiers to a target application as possible, e.g. an instrument may be represented by an ISIN, CUSIP or Bloomberg identifier.\n\nIdentifiers do not make sense for all types of data, so the `id` property is therefore optional, but some derived types may choose to require at least one identifier. Identifier values SHOULD always be of type string.",
        title="Id",
    )


class FDC3EventType(Enum):
    USER_CHANNEL_CHANGED = "USER_CHANNEL_CHANGED"


class FDC3Event(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    type: FDC3EventType
    details: Dict[str, Any] = Field(
        ...,
        description="Additional details of the event, such as the `currentChannelId` for a CHANNEL_CHANGED event.",
        title="Event details",
    )


class IntentResult1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    context: context_1.Schema


class IntentResult(RootModel[Union[IntentResult1, IntentResult2, Dict[str, Any]]]):
    root: Union[IntentResult1, IntentResult2, Dict[str, Any]] = Field(
        ..., title="IntentResult"
    )


# Common definitions
class ConnectionAttemptUuid(RootModel[str]):
    root: str = Field(
        default_factory=lambda: str(uuid.uuid4()),
        description="Unique identifier for a for an attempt to connect to a Desktop Agent. A Unique UUID should be used in the first (WCP1Hello) message and should be quoted in all subsequent messages to link them to the same connection attempt.",
        title="Connection Attempt UUID",
    )


class RequestUuid(RootModel[str]):
    root: str = Field(
        default_factory=lambda: str(uuid.uuid4()),
        description="Unique identifier for a request or event message. Required in all message types.",
        title="Request UUID",
    )


class ResponseUuid(RootModel[str]):
    root: str = Field(
        default_factory=lambda: str(uuid.uuid4()),
        description="Unique identifier for a response to a specific message and must always be accompanied by a RequestUuid.",
        title="Response UUID",
    )


class EventUuid(RootModel[str]):
    root: str = Field(
        default_factory=lambda: str(uuid.uuid4()),
        description="Unique identifier for an event message sent from a Desktop Agent to an app.",
        title="Event UUID",
    )


class ListenerUuid(RootModel[str]):
    root: str = Field(
        default_factory=lambda: str(uuid.uuid4()),
        description="Unique identifier for a `listener` object returned by a Desktop Agent to an app in response to addContextListener, addIntentListener or one of the PrivateChannel event listeners and used to identify it in messages (e.g. when unsubscribing).",
        title="Listener UUID",
    )


class Timestamp(RootModel[str]):
    root: str = Field(
        default_factory=lambda: datetime.now().isoformat(),
        description="Timestamp at which the message was generated.",
        title="Timestamp",
    )


class ErrorMessages(
    RootModel[Union[OpenError, ResolveError, ResultError, ChannelError, BridgingError]]
):
    root: Union[OpenError, ResolveError, ResultError, ChannelError, BridgingError]


class PrivateChannelEventListenerTypes(Enum):
    onAddContextListener = "onAddContextListener"
    onUnsubscribe = "onUnsubscribe"
    onDisconnect = "onDisconnect"
